# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('ano_modelo', models.CharField(max_length=10)),
                ('km', models.CharField(max_length=20)),
                ('combustivel', models.CharField(max_length=20)),
                ('preco', models.CharField(max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcar.Marca')),
            ],
        ),
    ]
