# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0002_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='opcionais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopcar.Opcionais'),
        ),
    ]
