# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0003_auto_20160324_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoOpcionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcionais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopcar.Opcionais')),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='opcionais',
        ),
        migrations.AddField(
            model_name='veiculoopcionais',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcar.Veiculo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='opcionais',
            field=models.ManyToManyField(through='shopcar.VeiculoOpcionais', to='shopcar.Opcionais'),
        ),
    ]
