# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0005_auto_20160324_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='opcionais',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
