# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0007_auto_20160514_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='veiculo_id',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='veiculo_hash',
            field=models.CharField(default=datetime.datetime(2016, 5, 14, 6, 18, 34, 694452, tzinfo=utc), max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
