# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0008_auto_20160514_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='veiculo_hash',
            new_name='hash_veiculo',
        ),
    ]
