# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0009_auto_20160514_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='hash_veiculo',
            new_name='veiculo_id',
        ),
    ]
